# Generated by Django 4.1.5 on 2023-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
