# Generated by Django 4.1.5 on 2023-01-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
